language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo64-7.0
- Pharo-7.0
- Pharo-6.1
matrix:
  allow_failures:
  - smalltalk: Pharo64-7.0
  - smalltalk: Pharo-7.0
  fast_finish: true
before_deploy:
- cp "${SMALLTALK_CI_IMAGE}" "Boardwalk.image"
- cp "${SMALLTALK_CI_CHANGES}" "Boardwalk.changes"
- zip -q "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip" "Boardwalk.image" "Boardwalk.changes"
deploy:
  provider: releases
  api_key:
    secure: L1loEGP2rLH9jeLt5sriAFrx+OwM2yK4lHKTgLRXQYZlpqdwgyL0xkag1/FCJAiokueqvik5GQ0JJiVWF3MCEz1Lvgm8xugox3qpR/fIZzeChkLl9VaPya1w4FrjN2HSIozbFO/spZG2bYMbJWoxGlTUEJXoqzOCJvFJYAW8E+zP2IQR3Zs5O07VqkDuEUVZWmY6vbNodaU4E5VkybNhePhdiG8GDjkrmYPINI4nV/HneKAm01pKieXeVyZMvozYTCAt2sv7Q0DF516ZzjxWh08QV9nYtTWFG82uf+OQI2M6TYqq/V/SlRcm2s6fhhv2gb0NOvs3qcQ8RZnIoLkrn3RUbaJOQGwgwfMgc4ceWdRFiszp4aQqjOIvimpZcrJOPbZrrm3jPxg9gmfjxv19g2Dn/apHH1WU847gOD8wXRmORYgYtN0YdTKeaBG2lhsscU6VrXHR4scJk74viy23Ynf77nmQADSD8t6f0dczPmq2ETRj6X+NrU+iAi3nLnVAY79pH0pMTql60RTOR4FcE1QLplqmnvgQw79AjJDayZVCCM5/wFc8G2+NffvrbyHw8gvU58wZt+psAB+++BlcaBpNAsXvSnvc5ppopOoaITzO1HD6hCfVPiMwBCO8hBoY2vQMcT/LTdS1sdN3i/JfoKOYOT8pbmkk0O4alT9qDpY=
  file: "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip"
  skip_cleanup: true
  on:
    repo: ba-st/Boardwalk
    tags: true
