name: Build

on:
  pull_request:
  push:

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ Pharo64-8.0, Pharo64-7.0, Pharo32-7.0, Pharo32-6.1 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: ba-st-actions/setup-smalltalkCI@v2.3.0
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - run: env
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 15
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./_builds/coveralls_results.json
